### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by modestegougbedji** [botamp/botamp-wordpress#3]
Here are the errors found during the actication of the plugin with wordpress 4.6.2
1- the API key does not work, it does not make a good connection to app.botamp.com.

2- Import items does not list items, but Javascript counts the number of items.

3- When I activate the plugin in a local wordpress installation on WampServer and without an internet connection, the plugin triggers an error (CURL) for a connection to app.botamp.com of which it blocks all the pages of the administration space Wordpress.

![bot1](https://cloud.githubusercontent.com/assets/22322635/21955011/58e1b564-d9fd-11e6-8d91-1b620412c21b.PNG)
![bot2](https://cloud.githubusercontent.com/assets/22322635/21955014/58e7853e-d9fd-11e6-8ad0-5a76d0bc4729.PNG)
![bot3](https://cloud.githubusercontent.com/assets/22322635/21955012/58e3e0a0-d9fd-11e6-8f4f-be4a3f33dbec.PNG)
![img_0488](https://cloud.githubusercontent.com/assets/22322635/21955013/58e58194-d9fd-11e6-9b31-a4b0af369248.JPG)
![img_0489](https://cloud.githubusercontent.com/assets/22322635/21955015/58e94284-d9fd-11e6-8568-c0f559ff0ac9.JPG)

**Comment by ousmanedev** [comment]
Thank you for opening this issue.
Concerning the **invalid api key problem**, can you please make sure the page is activated.
To activate a page : 
- Go to _pages_
- Click on the _Dashboard_ link on the specific _page_ item
- Then, click on _Settings_, in the top menu bar
- And hit the _Activate page_ button

**Comment by modestegougbedji** [comment]
Yes the page is activated


![bot4](https://cloud.githubusercontent.com/assets/22322635/21955366/7df4ecec-da05-11e6-8bb7-3bda2c7c1fab.PNG)

**Comment by modestegougbedji** [comment]
When I insert the key API and I restart the wamp server, here is the error that blocks access to all pages of administration

![bot5](https://cloud.githubusercontent.com/assets/22322635/21955381/e9dbf374-da05-11e6-9b65-24041fe07ffd.PNG)

**Comment by ousmanedev** [comment]
This error is due to an issue in your environment (which I can see is WAMP) with curl. Please upgrade it to a recent version.

**Comment by modestegougbedji** [comment]
this version wampserver is : 3.0.6

**Comment by ousmanedev** [comment]
Then you can either try to look at some suggestions here https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate, or directly use apache+php+mysql instead of WAMP

**Comment by ousmanedev** [comment]
I'm closing this, since the error encountered is not due to Botamp but to your local installation.
The warning showing by error problem has been fixed here #6 
Thanks !
